### ISSUE TITLE
Overstepping permissions?

### ISSUE THREAD

**Issue by Nexuist** [clundie/VideoFixer#1]
When I try to install the Chrome extension, Chrome's dialog says:

* Read and change all your data on the websites you visit

Is this really necessary? From what i can tell, all this extension does is apply some minor CSS to every page. Is there another, less extreme permission that will allow you to do the same thing? 

I may be wrong here, and this permission may actually be vital, but I hope you understand my concern.

Thank you very much.

**Comment by clundie** [comment]
As far as I could tell, it was necessary to ask for this permission, as the CSS styles are injected everywhere. There is no JavaScript, so none of your data can ever be changed or read or sent anywhere, but to my knowledge there is not a way to indicate that to the user. I'll close this issue for now but will keep this in mind if I find something better. Thanks.

**Comment by Nexuist** [comment]
Ah, ok. Just wanted to make sure it was essential. Thanks very much for the quick reply.
