### ISSUE TITLE
Can you please help me figure out why decreasing opacity fixes the issue?

### ISSUE THREAD

**Issue by elchiapp** [clundie/VideoFixer#5]
Ok this isn't really an issue but a crazy effort at trying to figure out why the hell we get this yellow tint on fullscreen videos in both Chrome and Safari (haven't tried other browsers). First of all **thank you so much** for showing me an alternative (easier) way to fix this issue permanently.

I'm on macOS 10.15.4 (MBP 13" Early 2015). Why does changing the size of the cursor in Accessibility -> Display or decreasing the video element's `opacity` to a value <= 0.998 make the yellow tint go away?

What is going on? 😂 And how did you get to the .996? Thanks again!

**Comment by clundie** [comment]
Thanks for asking. I think the `opacity` value came from 254 ÷ 255. Anything higher than this had no effect.

I don't know the details of why the bug happens. My hunch is that when a video is playing full-screen with nothing else visible on the screen, the computer renders the video in a special way that saves energy (battery life). And sometimes it doesn't look good. Lowering the `opacity` seems to bypass the energy-saving mode. There are other CSS rules that can do the same thing, like using `translate` to move the video a little bit, or make it a bit larger or smaller. I've also seen that subtitles will "fix" the video as long as they are visible, and it goes back to "ugly" when the subtitles are not visible.
